### ISSUE TITLE
Instruction not followed 

### ISSUE THREAD

**Issue by ezehlivinus** [Taeyhung/variable-assignment-solution#1]
Please @Taeyhung 

Go through the instruction of this assignment and be sure you met all requirements.

**Comment by ezehlivinus** [comment]
Check on how to declare variable using the let keyword....

**Comment by Taeyhung** [comment]
https://github.com/Taeyhung/variable-assignment-solution

**Comment by Taeyhung** [comment]
Thank you, sir
